version: '3.9'

services:
  ctf-nginx:
    image: nginx:latest
    container_name: ctf-nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./src/robots.txt:/etc/nginx/robots.txt
    restart: always
    depends_on: ["ctf-php"]
  ctf-php:
    container_name: ctf-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
        - ./src:/var/www/html
        - ./app.php:/var/www/config/app.php
        - ./flag:/tmp/flag
    depends_on: ["ctf-db"]
  ctf-db:
    container_name: ctf-db
    image: hypriot/rpi-mysql
    command: mysqld --innodb_use_native_aio=0
    restart: always
    environment:
      MYSQL_DATABASE: competition
      MYSQL_USER: competition
      MYSQL_PASSWORD: Password!1122
      MYSQL_ROOT_PASSWORD: P@ssw0rd!1222
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
volumes:
  mysql-data: {}

